//! Support for the Claude Remote Control single-sweep flow:
//!
//! 1. Granting workspace trust for a worktree by writing the same
//!    `~/.claude.json` entry that running `claude` there and accepting the
//!    trust prompt would write. Only ever called from an explicit user action
//!    in the UI — the click IS the consent.
//! 2. Writing a `CLAUDE.local.md` handoff file into the worktree so the remote
//!    session starts already knowing the task (Claude Code auto-reads it from
//!    its working directory; `claude remote-control` itself cannot accept an
//!    initial prompt).
//!
//! Empirically verified against Claude Code 2.1.233 (2026-08-17):
//! - `projects` keys in `~/.claude.json` use FORWARD slashes
//!   (e.g. `"C:/PROJECTS/kgp-vibe-kanban"`); backslash keys never match.
//! - On Windows both the 8.3 short-name form (`KENRIC~1.GOL`) and the long
//!   form of the same path may be consulted, so both are written.

use std::path::{Path, PathBuf};

use serde_json::{Map, Value, json};

/// The field set a genuine CLI-written trust entry carries. Extra fields are
/// harmless; `hasTrustDialogAccepted` is the one the trust check reads.
fn trust_entry() -> Value {
    json!({
        "allowedTools": [],
        "mcpContextUris": [],
        "mcpServers": {},
        "enabledMcpjsonServers": [],
        "disabledMcpjsonServers": [],
        "hasTrustDialogAccepted": true,
        "projectOnboardingSeenCount": 0,
        "hasClaudeMdExternalIncludesApproved": false,
        "hasClaudeMdExternalIncludesWarningShown": false,
        "hasCompletedProjectOnboarding": true
    })
}

/// Forward-slash key forms for a worktree path: the path as given, plus its
/// canonicalized (long-name) form when that differs.
fn trust_key_forms(worktree: &Path) -> Vec<String> {
    let to_key = |p: &Path| p.to_string_lossy().replace('\\', "/");
    let mut keys = vec![to_key(worktree)];
    if let Ok(canonical) = std::fs::canonicalize(worktree) {
        // canonicalize on Windows yields \\?\C:\... — strip the prefix.
        let s = canonical.to_string_lossy().replace('\\', "/");
        let s = s.strip_prefix("//?/").map(str::to_string).unwrap_or(s);
        if !keys.contains(&s) {
            keys.push(s);
        }
    }
    keys
}

/// Add trust entries for `worktree` to the given claude config file
/// (`~/.claude.json` in production; parameterised for tests). Additive only:
/// existing entries are never modified or removed.
pub fn grant_workspace_trust(config_path: &Path, worktree: &Path) -> Result<Vec<String>, String> {
    let raw = std::fs::read_to_string(config_path)
        .map_err(|e| format!("cannot read {}: {e}", config_path.display()))?;
    let mut root: Value =
        serde_json::from_str(&raw).map_err(|e| format!("claude config is not valid JSON: {e}"))?;

    let projects = root
        .as_object_mut()
        .ok_or("claude config root is not an object")?
        .entry("projects")
        .or_insert_with(|| Value::Object(Map::new()));
    let projects = projects
        .as_object_mut()
        .ok_or("claude config `projects` is not an object")?;

    let keys = trust_key_forms(worktree);
    for key in &keys {
        match projects.get_mut(key) {
            Some(Value::Object(existing)) => {
                existing.insert("hasTrustDialogAccepted".into(), Value::Bool(true));
            }
            _ => {
                projects.insert(key.clone(), trust_entry());
            }
        }
    }

    let serialized = serde_json::to_string_pretty(&root)
        .map_err(|e| format!("failed to serialize claude config: {e}"))?;
    std::fs::write(config_path, serialized)
        .map_err(|e| format!("cannot write {}: {e}", config_path.display()))?;
    Ok(keys)
}

/// Default location of the Claude Code config on this machine.
pub fn claude_config_path() -> Option<PathBuf> {
    dirs::home_dir().map(|home| home.join(".claude.json"))
}

const HANDOFF_MARKER: &str = "<!-- generated by Vibe Kanban Claude Remote Control -->";

/// Build the CLAUDE.local.md handoff content.
pub fn handoff_markdown(
    workspace_name: &str,
    branch: &str,
    task_description: Option<&str>,
) -> String {
    let task = task_description
        .filter(|t| !t.trim().is_empty())
        .unwrap_or("(no task description was recorded for this workspace)");
    format!(
        "{HANDOFF_MARKER}\n# Vibe Kanban handoff\n\n\
         This session is connected to Vibe Kanban workspace **{workspace_name}** \
         on branch `{branch}`.\n\n\
         ## Task\n\n{task}\n\n\
         Please read the current repo state (`git status`, `git log`, recent \
         diffs) before making changes — another agent may already have made \
         progress on this task.\n"
    )
}

/// Write the handoff file into the worktree, and keep it out of `git status`
/// by appending it to the repo's `info/exclude` (never `.gitignore`, which
/// would dirty the working tree).
///
/// Overwrites only files this feature wrote before (identified by the marker);
/// a user- or repo-provided CLAUDE.local.md is left untouched.
pub fn write_handoff_file(worktree: &Path, content: &str) -> Result<(), String> {
    let target = worktree.join("CLAUDE.local.md");

    if let Ok(existing) = std::fs::read_to_string(&target)
        && !existing.contains(HANDOFF_MARKER)
    {
        return Err("worktree already has a CLAUDE.local.md not written by Vibe Kanban".into());
    }

    std::fs::write(&target, content).map_err(|e| format!("cannot write handoff file: {e}"))?;

    // Best-effort exclude. In a linked worktree `.git` is a FILE containing
    // `gitdir: <per-worktree dir>`; git resolves info/exclude against the
    // COMMON dir, reached via that dir's `commondir` pointer file.
    if let Some(common) = resolve_git_common_dir(worktree) {
        let exclude = common.join("info").join("exclude");
        let already = std::fs::read_to_string(&exclude)
            .map(|s| s.lines().any(|l| l.trim() == "CLAUDE.local.md"))
            .unwrap_or(false);
        if !already {
            if let Some(parent) = exclude.parent() {
                let _ = std::fs::create_dir_all(parent);
            }
            let mut body = std::fs::read_to_string(&exclude).unwrap_or_default();
            if !body.is_empty() && !body.ends_with('\n') {
                body.push('\n');
            }
            body.push_str("CLAUDE.local.md\n");
            if let Err(e) = std::fs::write(&exclude, body) {
                tracing::warn!("could not update info/exclude: {e}");
            }
        }
    }

    Ok(())
}

/// Resolve the common git dir for `worktree`, following the `.git` pointer
/// file of linked worktrees. Returns None when the path is not a git worktree
/// root (e.g. a multi-repo workspace root), in which case no exclude is needed.
fn resolve_git_common_dir(worktree: &Path) -> Option<PathBuf> {
    let dot_git = worktree.join(".git");
    let git_dir = if dot_git.is_dir() {
        dot_git
    } else if dot_git.is_file() {
        let content = std::fs::read_to_string(&dot_git).ok()?;
        let rel = content.strip_prefix("gitdir:")?.trim();
        let p = PathBuf::from(rel);
        if p.is_absolute() { p } else { worktree.join(p) }
    } else {
        return None;
    };

    // A per-worktree dir carries a `commondir` pointer; the main .git does not.
    match std::fs::read_to_string(git_dir.join("commondir")) {
        Ok(common) => {
            let p = PathBuf::from(common.trim());
            Some(if p.is_absolute() { p } else { git_dir.join(p) })
        }
        Err(_) => Some(git_dir),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(name: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("vk-rc-support-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    #[test]
    fn trust_keys_use_forward_slashes() {
        let d = temp_dir("keys");
        let keys = trust_key_forms(&d);
        assert!(!keys.is_empty());
        for k in &keys {
            assert!(!k.contains('\\'), "backslash key would never match: {k}");
        }
    }

    #[test]
    fn grant_is_additive_and_idempotent() {
        let d = temp_dir("grant");
        let cfg = d.join(".claude.json");
        std::fs::write(
            &cfg,
            r#"{"projects":{"C:/existing":{"hasTrustDialogAccepted":true,"allowedTools":["x"]}},"other":"kept"}"#,
        )
        .unwrap();

        let wt = d.join("worktree");
        std::fs::create_dir_all(&wt).unwrap();
        grant_workspace_trust(&cfg, &wt).unwrap();
        grant_workspace_trust(&cfg, &wt).unwrap(); // idempotent

        let v: Value = serde_json::from_str(&std::fs::read_to_string(&cfg).unwrap()).unwrap();
        assert_eq!(v["other"], "kept");
        assert_eq!(v["projects"]["C:/existing"]["allowedTools"][0], "x");
        let granted = v["projects"]
            .as_object()
            .unwrap()
            .iter()
            .filter(|(k, _)| k.contains("worktree"))
            .count();
        assert!(granted >= 1);
        for (_, entry) in v["projects"].as_object().unwrap() {
            assert_eq!(entry["hasTrustDialogAccepted"], true);
        }
    }

    #[test]
    fn handoff_respects_foreign_claude_local_md() {
        let d = temp_dir("handoff");
        std::fs::write(d.join("CLAUDE.local.md"), "user's own notes").unwrap();
        let err = write_handoff_file(&d, &handoff_markdown("ws", "main", None));
        assert!(err.is_err(), "must not clobber a user's file");
        assert_eq!(
            std::fs::read_to_string(d.join("CLAUDE.local.md")).unwrap(),
            "user's own notes"
        );
    }

    #[test]
    fn handoff_writes_and_overwrites_own_file() {
        let d = temp_dir("handoff2");
        write_handoff_file(&d, &handoff_markdown("ws", "main", Some("do the thing"))).unwrap();
        let first = std::fs::read_to_string(d.join("CLAUDE.local.md")).unwrap();
        assert!(first.contains("do the thing"));
        assert!(first.contains("Vibe Kanban"));
        // second write (new task) overwrites our own file
        write_handoff_file(&d, &handoff_markdown("ws", "main", Some("new task"))).unwrap();
        let second = std::fs::read_to_string(d.join("CLAUDE.local.md")).unwrap();
        assert!(second.contains("new task"));
    }

    #[test]
    fn exclude_written_through_worktree_pointer_file() {
        let d = temp_dir("exclude");
        // simulate a linked worktree: .git FILE -> per-worktree dir -> commondir
        let common = d.join("main-repo-git");
        let wt_gitdir = common.join("worktrees").join("wt1");
        std::fs::create_dir_all(&wt_gitdir).unwrap();
        std::fs::write(wt_gitdir.join("commondir"), "../..\n").unwrap();
        let wt = d.join("wt");
        std::fs::create_dir_all(&wt).unwrap();
        std::fs::write(wt.join(".git"), format!("gitdir: {}", wt_gitdir.display())).unwrap();

        write_handoff_file(&wt, &handoff_markdown("ws", "main", None)).unwrap();

        let exclude = std::fs::read_to_string(common.join("info").join("exclude")).unwrap();
        assert!(exclude.lines().any(|l| l.trim() == "CLAUDE.local.md"));

        // idempotent: run again, still exactly one entry
        write_handoff_file(&wt, &handoff_markdown("ws", "main", None)).unwrap();
        let exclude = std::fs::read_to_string(common.join("info").join("exclude")).unwrap();
        assert_eq!(
            exclude
                .lines()
                .filter(|l| l.trim() == "CLAUDE.local.md")
                .count(),
            1
        );
    }
}
