<#
.SYNOPSIS
  Generates docker/kgp-local/.env for this Windows machine and checks Docker.

.EXAMPLE
  .\setup.ps1
  .\setup.ps1 -ReposDir D:\code -Up
  .\setup.ps1 -Force          # overwrite an existing .env

.NOTES
  Written for Windows PowerShell 5.1 — no ternary, no ??, no && chaining.
#>
[CmdletBinding()]
param(
  [string] $ReposDir,
  [int]    $Port = 3000,
  [int]    $PreviewPort = 3001,
  [switch] $Force,
  [switch] $Up
)

$ErrorActionPreference = 'Stop'
$here    = Split-Path -Parent $MyInvocation.MyCommand.Path
$envPath = Join-Path $here '.env'

function Write-Step { param($m) Write-Host "==> $m" -ForegroundColor Cyan }
function Write-Ok   { param($m) Write-Host "    $m" -ForegroundColor Green }
function Write-Warn { param($m) Write-Host "    $m" -ForegroundColor Yellow }

Write-Step 'Self-contained Vibe Kanban - Windows setup'

# --- .env guard --------------------------------------------------------------
if ((Test-Path $envPath) -and (-not $Force)) {
  Write-Warn ".env already exists. Re-run with -Force to regenerate it."
  Write-Warn "  $envPath"
  exit 0
}

# --- repos directory ---------------------------------------------------------
if (-not $ReposDir) {
  $candidates = @('C:\PROJECTS', (Join-Path $env:USERPROFILE 'Projects'), (Join-Path $env:USERPROFILE 'source\repos'))
  foreach ($c in $candidates) {
    if (Test-Path $c) { $ReposDir = $c; break }
  }
}
if (-not $ReposDir) {
  $ReposDir = Read-Host 'Folder containing your git repositories (e.g. C:\PROJECTS)'
}
if (-not (Test-Path $ReposDir)) {
  throw "Repos directory not found: $ReposDir"
}
$ReposDir = (Resolve-Path $ReposDir).Path
Write-Ok "repos      $ReposDir  ->  /repos"

# --- Claude Code profile -----------------------------------------------------
# Missing sources fall back to the committed ./noseed placeholders: Docker
# creates a *directory* at a nonexistent bind-mount source, which would turn
# ~\.claude.json into a folder.
$claudeDir  = Join-Path $env:USERPROFILE '.claude'
$claudeJson = Join-Path $env:USERPROFILE '.claude.json'

if (Test-Path (Join-Path $claudeDir '.credentials.json')) {
  Write-Ok "claude     $claudeDir (credentials found, will be copied in once)"
} elseif (Test-Path $claudeDir) {
  Write-Warn "claude     $claudeDir exists but has no .credentials.json"
  Write-Warn "           log in inside the container after first start (see README)"
} else {
  Write-Warn "claude     no profile found; using ./noseed placeholder"
  $claudeDir = './noseed'
}
if (-not (Test-Path $claudeJson)) { $claudeJson = './noseed.json' }

# --- git identity ------------------------------------------------------------
$gitName  = ''
$gitEmail = ''
try { $gitName  = (git config --global user.name)  } catch {}
try { $gitEmail = (git config --global user.email) } catch {}
if ([string]::IsNullOrWhiteSpace($gitName))  { $gitName  = 'Vibe Kanban' }
if ([string]::IsNullOrWhiteSpace($gitEmail)) { $gitEmail = 'vibe-kanban@localhost' }
Write-Ok "commits as $gitName <$gitEmail>"

# --- write .env --------------------------------------------------------------
$content = @"
# Generated by setup.ps1 for Windows. Git-ignored. Safe to edit by hand.

VK_REPOS_DIR=$ReposDir

VK_CLAUDE_DIR=$claudeDir
VK_CLAUDE_JSON=$claudeJson

VK_PORT=$Port
VK_PREVIEW_PORT=$PreviewPort

GIT_USER_NAME=$gitName
GIT_USER_EMAIL=$gitEmail

# Only needed if the container cannot use a seeded OAuth token.
ANTHROPIC_API_KEY=

RUST_LOG=info
DISABLE_WORKTREE_CLEANUP=
VK_ALLOWED_ORIGINS=
"@

[System.IO.File]::WriteAllText($envPath, $content, (New-Object System.Text.UTF8Encoding($false)))
Write-Ok "wrote $envPath"

# --- install mode marker -----------------------------------------------------
# Read by AGENTS.md before anything is built. Lives at the repo root because it
# describes the whole checkout, not just this directory. Git-ignored.
$repoRoot   = (Resolve-Path (Join-Path $here '..\..')).Path
$markerPath = Join-Path $repoRoot '.kgp-install-mode'

$marker = @"
# Generated by docker/kgp-local/setup.ps1. Git-ignored.
# Read by AGENTS.md before building or running. Do not commit.
MODE=LOCAL
SET_BY=docker/kgp-local/setup.ps1
SET_ON=$(Get-Date -Format 'yyyy-MM-dd')
API_BASE=
RELAY_BASE=
"@

# No-BOM UTF8, matching how .env is written above. Set-Content would emit a BOM
# under PS 5.1 and break naive KEY=VALUE parsers.
[System.IO.File]::WriteAllText($markerPath, $marker, (New-Object System.Text.UTF8Encoding($false)))
Write-Ok "install mode LOCAL -> $markerPath"

# --- docker preflight --------------------------------------------------------
Write-Step 'Checking Docker'
$dockerOk = $false
if (Get-Command docker -ErrorAction SilentlyContinue) {
  # Windows PowerShell 5.1 turns a native command's stderr into NativeCommandError
  # records, so relax ErrorActionPreference and swallow the stream rather than
  # redirecting it. $LASTEXITCODE stays authoritative either way.
  $prevEAP = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  try {
    $null = & docker info 2>&1 | Out-String
    if ($LASTEXITCODE -eq 0) { $dockerOk = $true }
  } catch {
    $dockerOk = $false
  } finally {
    $ErrorActionPreference = $prevEAP
  }
}

if ($dockerOk) {
  Write-Ok 'Docker engine is reachable.'
} else {
  Write-Warn 'Docker engine is NOT reachable.'
  $wsl = Get-CimInstance -ClassName Win32_OptionalFeature -Filter "Name='Microsoft-Windows-Subsystem-Linux'" -ErrorAction SilentlyContinue
  if ($wsl -and $wsl.InstallState -ne 1) {
    Write-Warn 'WSL2 is not installed. Docker Desktop needs it for Linux containers.'
    Write-Warn 'In an ADMIN PowerShell, run:   wsl --install     then reboot.'
  } else {
    Write-Warn 'Start Docker Desktop and wait for it to report Running.'
  }
  Write-Warn 'Then: docker compose up -d --build'
  exit 1
}

# --- go ----------------------------------------------------------------------
if ($Up) {
  Write-Step 'Building and starting (first build takes 10-20 min)'
  Push-Location $here
  try { docker compose up -d --build } finally { Pop-Location }
  Write-Ok "Open http://localhost:$Port"
} else {
  Write-Host ''
  Write-Host '  Next:  cd docker\kgp-local' -ForegroundColor White
  Write-Host '         docker compose up -d --build' -ForegroundColor White
  Write-Host "         open http://localhost:$Port" -ForegroundColor White
}
