#!/usr/bin/env bash
#
# Generates docker/kgp-local/.env for this macOS (or Linux) machine and checks
# Docker.
#
#   ./setup.sh
#   ./setup.sh --repos ~/code --up
#   ./setup.sh --force            # overwrite an existing .env
#
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
env_path="$here/.env"

repos_dir=""
port=3000
preview_port=3001
force=0
up=0

while [ $# -gt 0 ]; do
  case "$1" in
    --repos)        repos_dir="$2"; shift 2 ;;
    --port)         port="$2"; shift 2 ;;
    --preview-port) preview_port="$2"; shift 2 ;;
    --force)        force=1; shift ;;
    --up)           up=1; shift ;;
    -h|--help)      sed -n '3,10p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

step() { printf '\033[36m==> %s\033[0m\n' "$1"; }
ok()   { printf '\033[32m    %s\033[0m\n' "$1"; }
warn() { printf '\033[33m    %s\033[0m\n' "$1"; }

case "$(uname -s)" in
  Darwin) host_os="macOS" ;;
  Linux)  host_os="Linux" ;;
  *)      host_os="$(uname -s)" ;;
esac
step "Self-contained Vibe Kanban - $host_os setup"

# --- .env guard --------------------------------------------------------------
if [ -f "$env_path" ] && [ "$force" -eq 0 ]; then
  warn ".env already exists. Re-run with --force to regenerate it."
  warn "  $env_path"
  exit 0
fi

# --- repos directory ---------------------------------------------------------
if [ -z "$repos_dir" ]; then
  for c in "$HOME/Projects" "$HOME/projects" "$HOME/code" "$HOME/src" "$HOME/dev"; do
    if [ -d "$c" ]; then repos_dir="$c"; break; fi
  done
fi
if [ -z "$repos_dir" ]; then
  read -r -p "Folder containing your git repositories (e.g. $HOME/Projects): " repos_dir
fi
repos_dir="${repos_dir/#\~/$HOME}"
if [ ! -d "$repos_dir" ]; then
  echo "Repos directory not found: $repos_dir" >&2
  exit 1
fi
repos_dir="$(cd "$repos_dir" && pwd)"
ok "repos      $repos_dir  ->  /repos"

# --- Claude Code profile -----------------------------------------------------
# Missing sources fall back to the committed ./noseed placeholders: Docker
# creates a *directory* at a nonexistent bind-mount source, which would turn
# ~/.claude.json into a folder.
claude_dir="$HOME/.claude"
claude_json="$HOME/.claude.json"

if [ -f "$claude_dir/.credentials.json" ]; then
  ok "claude     $claude_dir (credentials found, will be copied in once)"
elif [ -d "$claude_dir" ]; then
  if [ "$host_os" = "macOS" ]; then
    warn "claude     profile found, but macOS keeps OAuth tokens in the Keychain,"
    warn "           not in .credentials.json - so there is nothing to copy in."
    warn "           After first start, log in inside the container:"
    warn "             docker compose exec vibe-kanban npx -y @anthropic-ai/claude-code /login"
    warn "           (ANTHROPIC_API_KEY works for normal runs but disables Claude"
    warn "            Remote Control, which requires a subscription login.)"
  else
    warn "claude     $claude_dir exists but has no .credentials.json"
    warn "           log in inside the container after first start (see README)"
  fi
else
  warn "claude     no profile found; using ./noseed placeholder"
  claude_dir="./noseed"
fi
[ -f "$claude_json" ] || claude_json="./noseed.json"

# --- git identity ------------------------------------------------------------
git_name="$(git config --global user.name 2>/dev/null || true)"
git_email="$(git config --global user.email 2>/dev/null || true)"
[ -n "$git_name" ]  || git_name="Vibe Kanban"
[ -n "$git_email" ] || git_email="vibe-kanban@localhost"
ok "commits as $git_name <$git_email>"

# --- write .env --------------------------------------------------------------
cat > "$env_path" <<EOF
# Generated by setup.sh for $host_os. Git-ignored. Safe to edit by hand.

VK_REPOS_DIR=$repos_dir

VK_CLAUDE_DIR=$claude_dir
VK_CLAUDE_JSON=$claude_json

VK_PORT=$port
VK_PREVIEW_PORT=$preview_port

GIT_USER_NAME=$git_name
GIT_USER_EMAIL=$git_email

# Usually required on macOS, where the OAuth token lives in the Keychain and
# cannot be seeded into the container from a file.
ANTHROPIC_API_KEY=

RUST_LOG=info
DISABLE_WORKTREE_CLEANUP=
VK_ALLOWED_ORIGINS=
EOF
ok "wrote $env_path"

# --- install mode marker -----------------------------------------------------
# Read by AGENTS.md before anything is built. Lives at the repo root because it
# describes the whole checkout, not just this directory. Git-ignored.
repo_root="$(cd "$here/../.." && pwd)"
marker_path="$repo_root/.kgp-install-mode"

cat > "$marker_path" <<EOF
# Generated by docker/kgp-local/setup.sh. Git-ignored.
# Read by AGENTS.md before building or running. Do not commit.
MODE=LOCAL
SET_BY=docker/kgp-local/setup.sh
SET_ON=$(date +%Y-%m-%d)
API_BASE=
RELAY_BASE=
EOF
ok "install mode LOCAL -> $marker_path"

# --- docker preflight --------------------------------------------------------
step "Checking Docker"
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  ok "Docker engine is reachable ($(uname -m))."
else
  warn "Docker engine is NOT reachable."
  if [ "$host_os" = "macOS" ]; then
    warn "Install/start Docker Desktop:  brew install --cask docker  (then launch it)"
  else
    warn "Start the Docker daemon, then re-run."
  fi
  warn "Then: docker compose up -d --build"
  exit 1
fi

# --- go ----------------------------------------------------------------------
if [ "$up" -eq 1 ]; then
  step "Building and starting (first build takes 10-20 min)"
  ( cd "$here" && docker compose up -d --build )
  ok "Open http://localhost:$port"
else
  echo
  echo "  Next:  cd docker/kgp-local"
  echo "         docker compose up -d --build"
  echo "         open http://localhost:$port"
fi
